CLASS zbp_r_rap100_atravpin DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zr_rap100_atravpin .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zbp_r_rap100_atravpin IMPLEMENTATION.
ENDCLASS.
